// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplicationConDB.Data;

#nullable disable

namespace WebApplicationConDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123161400_nuevasTabla")]
    partial class nuevasTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChessProject.Models.EstadisticasJugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Derrotas")
                        .HasColumnType("integer");

                    b.Property<int>("Empates")
                        .HasColumnType("integer");

                    b.Property<int>("JugadorId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidasJugadas")
                        .HasColumnType("integer");

                    b.Property<int>("PorBlancas")
                        .HasColumnType("integer");

                    b.Property<int>("PorNegras")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoTotalJugado")
                        .HasColumnType("integer");

                    b.Property<int>("Victorias")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EstadisticasJugadores", (string)null);
                });

            modelBuilder.Entity("ChessProject.Models.Jugador", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JugadorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JugadorId");

                    b.ToTable("Jugadores", (string)null);
                });

            modelBuilder.Entity("ChessProject.Models.Movimiento", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovimientoId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroTurno")
                        .HasColumnType("integer");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<string>("Pieza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PiezaCapturada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MovimientoId");

                    b.ToTable("Movimientos", (string)null);
                });

            modelBuilder.Entity("ChessProject.Models.Partida", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartidaId"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ganador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JugadorBlancasId")
                        .HasColumnType("integer");

                    b.Property<int>("JugadorNegrasId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoFin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoPartida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartidaId");

                    b.ToTable("Partidas", (string)null);
                });

            modelBuilder.Entity("WebApplicationConDB.Models.Roles", b =>
                {
                    b.Property<int>("IdRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRoles"));

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("IdRoles");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("WebApplicationConDB.Models.UserRoles", b =>
                {
                    b.Property<int>("IdUsers")
                        .HasColumnType("integer");

                    b.Property<int>("IdRoles")
                        .HasColumnType("integer");

                    b.HasKey("IdUsers", "IdRoles");

                    b.HasIndex("IdRoles");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("WebApplicationConDB.Models.Users", b =>
                {
                    b.Property<int>("IdUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsers"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Passwork")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsers");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WebApplicationConDB.Models.UserRoles", b =>
                {
                    b.HasOne("WebApplicationConDB.Models.Roles", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("IdRoles")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplicationConDB.Models.Users", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("IdUsers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplicationConDB.Models.Roles", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WebApplicationConDB.Models.Users", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
